[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
# Ensure storage layout for static analysis
extra_output = ["storageLayout"]
build_info = true
auto_detect_solc = true
